apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.servicename }}
  labels:
    app: {{ .Values.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
     app: {{ .Values.name }}
     version: {{ .Values.labels.version }}